### ISSUE TITLE
Admin user not created for influxdb

### ISSUE THREAD

**Issue by oxr463** [longhorn/upgrade-responder#35]
I deployed a new instance of the upgrade-responder chart but the pod was crashlooping. This is what was in the logs:

```
time="2022-07-06T13:42:48Z" level=debug msg="GeoDB opened" 
time="2022-07-06T13:42:48Z" level=debug msg="InfluxDB connection established" 
time="2022-07-06T13:42:48Z" level=fatal msg="error authorizing query: create admin user first or disable authentication" 
```

This is what I have in my values:

```
secret:
  influxDBPassword: ""
  influxDBUrl: ""
  influxDBUser: ""
  managed: false
  name: upgrade-responder-secrets
```
